### PR TITLE
Fix insert transform only keys in first row

### LINKED ISSUE #130: Transforms do not transform any values in `insert!` that are not present in the first row
Not really 100% clear that this should be allowed or ultimately will work anyway, but it causes Honey SQL compilation to fail because the column is untransformed which is misleading. I spent a solid 30 minutes trying to figure out why transformation wasn't working util I figured out what was going on.

Failing test for `toucan2.tools.transformed-test`:

```clj
(derive ::venues.edn-category ::test/venues)

(transformed/deftransforms ::venues.edn-category
  {:category {:in  pr-str
              :out (fn [s]
                     (binding [*read-eval* false]
                       (read-string s)))}})

(deftest ^:parallel transform-insert-rows-test
  (is (= [{:name "Venue 1"}
          {:name "Venue 2", :category "{:name \"Category 2\"}"}]
         (#'toucan2.tools.transformed/transform-insert-rows
          '[{:name "Venue 1"}
            {:name "Venue 2", :category {:name "Category 2"}}]
          (#'toucan2.tools.transformed/in-transforms ::venues.edn-category)))))
```

### PR DESCRIPTION
**Pull request by qnkhuat**
Fixes #130

### CODE REVIEW

File: src/toucan2/tools/transformed.clj [hunk 1]
```diff
@@ -281,20 +281,15 @@
...
-                         :let  [xform (get k->transform k)]
-                         :when xform]
-                     (fn [row]
-                       (update row k (fn [v]
-                                       (if (some? v)
-                                         (xform v)
-                                         v)))))
-        row-xform  (apply comp row-xforms)]
-    (map row-xform rows)))
+  (let [x-forms (for [[k transform] k->transform]
```
Comment (qnkhuat) [inline src/toucan2/tools/transformed.clj:286]: should we do the same for `transform-update-changes`? instead of loop through the row and checking if `k->transform` exists a transformation function, we'll build out an `xform` from `k->transform`.

a plus point with that approach is we don't have to do `into {}`, which might gives a better performance ?

**Review by camsaul — APPROVED** [review]
Cool, thanks for this

**Comment by camsaul** [comment]
This will go live in `1.0.524`
